// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagementApp.Data;

#nullable disable

namespace ProjectManagementApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120112339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProjectManagementApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Loyal46@hotmail.com",
                            FirstName = "Brenna",
                            LastName = "Reichert",
                            MiddleName = "Erica"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Aniya5@hotmail.com",
                            FirstName = "Archibald",
                            LastName = "Champlin",
                            MiddleName = "Trystan"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Reggie_Hickle@hotmail.com",
                            FirstName = "Antonetta",
                            LastName = "Walsh",
                            MiddleName = "Iliana"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Tressie.Marks54@hotmail.com",
                            FirstName = "Carmela",
                            LastName = "Douglas",
                            MiddleName = "Lura"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Clark41@gmail.com",
                            FirstName = "Montana",
                            LastName = "Brakus",
                            MiddleName = "Esta"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Mona82@yahoo.com",
                            FirstName = "Alexandro",
                            LastName = "Weimann",
                            MiddleName = "Christine"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Kaley_Will17@yahoo.com",
                            FirstName = "Carter",
                            LastName = "Carter",
                            MiddleName = "Sid"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Vaughn52@gmail.com",
                            FirstName = "Kendra",
                            LastName = "Kirlin",
                            MiddleName = "Dulce"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Yasmine_Witting20@gmail.com",
                            FirstName = "Thaddeus",
                            LastName = "Bogisich",
                            MiddleName = "Concepcion"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Beulah24@gmail.com",
                            FirstName = "Jacey",
                            LastName = "Langosh",
                            MiddleName = "Catharine"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Edwardo_Watsica@yahoo.com",
                            FirstName = "Cayla",
                            LastName = "Witting",
                            MiddleName = "Serena"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Tre76@gmail.com",
                            FirstName = "Claudia",
                            LastName = "Leannon",
                            MiddleName = "Anabelle"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Fleta.Berge@hotmail.com",
                            FirstName = "Nyasia",
                            LastName = "Rodriguez",
                            MiddleName = "Delores"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Nicolas_Jacobs51@yahoo.com",
                            FirstName = "Eleazar",
                            LastName = "Pouros",
                            MiddleName = "Ottilie"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Merl_Sporer23@gmail.com",
                            FirstName = "Reanna",
                            LastName = "Kuhic",
                            MiddleName = "Abigale"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Damien.Predovic28@yahoo.com",
                            FirstName = "Geovanny",
                            LastName = "Jenkins",
                            MiddleName = "Jaqueline"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Keenan.West@gmail.com",
                            FirstName = "Bill",
                            LastName = "Pacocha",
                            MiddleName = "Kelton"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Rashawn88@gmail.com",
                            FirstName = "Hortense",
                            LastName = "Lang",
                            MiddleName = "Garnett"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Richard46@hotmail.com",
                            FirstName = "Fiona",
                            LastName = "Bergstrom",
                            MiddleName = "Gay"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Abbie.Kling64@gmail.com",
                            FirstName = "Keira",
                            LastName = "Frami",
                            MiddleName = "Jedediah"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Blanca28@yahoo.com",
                            FirstName = "Jammie",
                            LastName = "Swift",
                            MiddleName = "Matteo"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Sean_Hilll@gmail.com",
                            FirstName = "Asia",
                            LastName = "Pfannerstill",
                            MiddleName = "Eleanora"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Dandre_Abbott@yahoo.com",
                            FirstName = "Erik",
                            LastName = "Hoeger",
                            MiddleName = "Ebony"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Toby_Hahn14@hotmail.com",
                            FirstName = "Marielle",
                            LastName = "Von",
                            MiddleName = "Kenton"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Rosina28@hotmail.com",
                            FirstName = "Marielle",
                            LastName = "Brekke",
                            MiddleName = "Andrew"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Wilford67@gmail.com",
                            FirstName = "Winfield",
                            LastName = "Fisher",
                            MiddleName = "Kaelyn"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Peter_Lesch15@gmail.com",
                            FirstName = "Ronaldo",
                            LastName = "Hoppe",
                            MiddleName = "Jeffery"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Leta35@hotmail.com",
                            FirstName = "Phoebe",
                            LastName = "Homenick",
                            MiddleName = "Lewis"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Charlie_Kovacek33@hotmail.com",
                            FirstName = "Meghan",
                            LastName = "Mann",
                            MiddleName = "Rafael"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Andres29@yahoo.com",
                            FirstName = "Luther",
                            LastName = "Powlowski",
                            MiddleName = "Curt"
                        },
                        new
                        {
                            Id = 31,
                            Email = "Coy_Fay72@yahoo.com",
                            FirstName = "Elody",
                            LastName = "Tillman",
                            MiddleName = "Melissa"
                        },
                        new
                        {
                            Id = 32,
                            Email = "Adonis_Kuhlman@gmail.com",
                            FirstName = "Phoebe",
                            LastName = "Robel",
                            MiddleName = "Freida"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Daisha52@yahoo.com",
                            FirstName = "Friedrich",
                            LastName = "Quitzon",
                            MiddleName = "Connie"
                        },
                        new
                        {
                            Id = 34,
                            Email = "Allen52@hotmail.com",
                            FirstName = "Shyanne",
                            LastName = "Rutherford",
                            MiddleName = "Joana"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Mallory_McDermott30@hotmail.com",
                            FirstName = "Samantha",
                            LastName = "Champlin",
                            MiddleName = "Aglae"
                        },
                        new
                        {
                            Id = 36,
                            Email = "Annabel37@hotmail.com",
                            FirstName = "Lourdes",
                            LastName = "Gusikowski",
                            MiddleName = "Litzy"
                        },
                        new
                        {
                            Id = 37,
                            Email = "Matteo_Feil37@hotmail.com",
                            FirstName = "Leopoldo",
                            LastName = "Lang",
                            MiddleName = "Dangelo"
                        },
                        new
                        {
                            Id = 38,
                            Email = "Joany93@gmail.com",
                            FirstName = "Wanda",
                            LastName = "Kirlin",
                            MiddleName = "Rocio"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Reinhold57@hotmail.com",
                            FirstName = "Erin",
                            LastName = "Lueilwitz",
                            MiddleName = "Hilma"
                        },
                        new
                        {
                            Id = 40,
                            Email = "Kaitlin_Kuphal8@gmail.com",
                            FirstName = "Junius",
                            LastName = "Collins",
                            MiddleName = "Heaven"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Edmond.Feeney28@hotmail.com",
                            FirstName = "Moses",
                            LastName = "Ritchie",
                            MiddleName = "Ally"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Yadira26@gmail.com",
                            FirstName = "Vinnie",
                            LastName = "Bruen",
                            MiddleName = "Ernesto"
                        },
                        new
                        {
                            Id = 43,
                            Email = "Colleen_Tremblay41@hotmail.com",
                            FirstName = "Gregory",
                            LastName = "Considine",
                            MiddleName = "John"
                        },
                        new
                        {
                            Id = 44,
                            Email = "Myrtle90@hotmail.com",
                            FirstName = "Abe",
                            LastName = "Wisozk",
                            MiddleName = "Jany"
                        },
                        new
                        {
                            Id = 45,
                            Email = "Alda_Runolfsson@hotmail.com",
                            FirstName = "Annalise",
                            LastName = "Reichel",
                            MiddleName = "Juliet"
                        },
                        new
                        {
                            Id = 46,
                            Email = "Sylvan_Collins8@hotmail.com",
                            FirstName = "Xavier",
                            LastName = "Ankunding",
                            MiddleName = "Doyle"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Lillie.Runolfsdottir82@hotmail.com",
                            FirstName = "Ezequiel",
                            LastName = "Rau",
                            MiddleName = "Merle"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Jamie0@hotmail.com",
                            FirstName = "Keira",
                            LastName = "Satterfield",
                            MiddleName = "Bertha"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Turner.Renner51@hotmail.com",
                            FirstName = "Brianne",
                            LastName = "Baumbach",
                            MiddleName = "Carole"
                        },
                        new
                        {
                            Id = 50,
                            Email = "Mustafa_Waelchi@gmail.com",
                            FirstName = "Alverta",
                            LastName = "Goyette",
                            MiddleName = "Nia"
                        });
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientCompany = "Wilderman - Okuneva",
                            ContractorCompany = "Denesik - Padberg",
                            EndDate = new DateTime(2025, 10, 24, 11, 52, 13, 779, DateTimeKind.Local).AddTicks(6095),
                            Name = "Project 1",
                            Priority = 2,
                            ProjectManagerId = 17,
                            StartDate = new DateTime(2023, 12, 13, 15, 12, 33, 103, DateTimeKind.Local).AddTicks(3083)
                        },
                        new
                        {
                            Id = 2,
                            ClientCompany = "Tillman - Cassin",
                            ContractorCompany = "Nicolas - Kuhic",
                            EndDate = new DateTime(2025, 7, 29, 19, 29, 59, 937, DateTimeKind.Local).AddTicks(1833),
                            Name = "Project 2",
                            Priority = 5,
                            ProjectManagerId = 1,
                            StartDate = new DateTime(2023, 7, 6, 2, 5, 54, 104, DateTimeKind.Local).AddTicks(1877)
                        },
                        new
                        {
                            Id = 3,
                            ClientCompany = "Runolfsson - O'Keefe",
                            ContractorCompany = "McCullough, Hyatt and Moore",
                            EndDate = new DateTime(2025, 1, 9, 9, 24, 48, 692, DateTimeKind.Local).AddTicks(4451),
                            Name = "Project 3",
                            Priority = 2,
                            ProjectManagerId = 43,
                            StartDate = new DateTime(2023, 1, 2, 9, 43, 26, 311, DateTimeKind.Local).AddTicks(3344)
                        },
                        new
                        {
                            Id = 4,
                            ClientCompany = "Steuber - Lueilwitz",
                            ContractorCompany = "Daugherty - Kreiger",
                            EndDate = new DateTime(2025, 9, 27, 20, 4, 35, 938, DateTimeKind.Local).AddTicks(7926),
                            Name = "Project 4",
                            Priority = 3,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2024, 11, 17, 12, 49, 43, 792, DateTimeKind.Local).AddTicks(6545)
                        },
                        new
                        {
                            Id = 5,
                            ClientCompany = "Rosenbaum Inc",
                            ContractorCompany = "Lesch, Stracke and Abshire",
                            EndDate = new DateTime(2025, 10, 2, 19, 33, 16, 877, DateTimeKind.Local).AddTicks(1450),
                            Name = "Project 5",
                            Priority = 1,
                            ProjectManagerId = 14,
                            StartDate = new DateTime(2023, 9, 10, 13, 42, 59, 113, DateTimeKind.Local).AddTicks(5000)
                        },
                        new
                        {
                            Id = 6,
                            ClientCompany = "O'Conner - Oberbrunner",
                            ContractorCompany = "West, Cruickshank and Stiedemann",
                            EndDate = new DateTime(2025, 4, 4, 7, 22, 5, 206, DateTimeKind.Local).AddTicks(1787),
                            Name = "Project 6",
                            Priority = 4,
                            ProjectManagerId = 22,
                            StartDate = new DateTime(2024, 3, 14, 3, 38, 40, 388, DateTimeKind.Local).AddTicks(4762)
                        },
                        new
                        {
                            Id = 7,
                            ClientCompany = "O'Conner - Schamberger",
                            ContractorCompany = "Schuppe and Sons",
                            EndDate = new DateTime(2025, 3, 14, 10, 37, 45, 187, DateTimeKind.Local).AddTicks(4194),
                            Name = "Project 7",
                            Priority = 2,
                            ProjectManagerId = 9,
                            StartDate = new DateTime(2023, 3, 13, 11, 15, 25, 542, DateTimeKind.Local).AddTicks(2612)
                        },
                        new
                        {
                            Id = 8,
                            ClientCompany = "Rowe, Beier and Bayer",
                            ContractorCompany = "Champlin LLC",
                            EndDate = new DateTime(2025, 2, 2, 12, 32, 34, 244, DateTimeKind.Local).AddTicks(4062),
                            Name = "Project 8",
                            Priority = 1,
                            ProjectManagerId = 49,
                            StartDate = new DateTime(2023, 10, 1, 18, 2, 56, 867, DateTimeKind.Local).AddTicks(8833)
                        },
                        new
                        {
                            Id = 9,
                            ClientCompany = "Nader, Marquardt and Johnson",
                            ContractorCompany = "Crona - Ullrich",
                            EndDate = new DateTime(2025, 9, 23, 1, 29, 56, 83, DateTimeKind.Local).AddTicks(5157),
                            Name = "Project 9",
                            Priority = 5,
                            ProjectManagerId = 42,
                            StartDate = new DateTime(2022, 12, 24, 4, 5, 47, 724, DateTimeKind.Local).AddTicks(3867)
                        },
                        new
                        {
                            Id = 10,
                            ClientCompany = "Cruickshank - Hudson",
                            ContractorCompany = "Sipes - Huel",
                            EndDate = new DateTime(2025, 8, 13, 13, 4, 45, 452, DateTimeKind.Local).AddTicks(3265),
                            Name = "Project 10",
                            Priority = 3,
                            ProjectManagerId = 50,
                            StartDate = new DateTime(2024, 7, 13, 21, 48, 42, 424, DateTimeKind.Local).AddTicks(1677)
                        },
                        new
                        {
                            Id = 11,
                            ClientCompany = "Schowalter, Borer and Kuhic",
                            ContractorCompany = "Farrell - Lueilwitz",
                            EndDate = new DateTime(2025, 3, 6, 14, 4, 44, 706, DateTimeKind.Local).AddTicks(8880),
                            Name = "Project 11",
                            Priority = 4,
                            ProjectManagerId = 14,
                            StartDate = new DateTime(2023, 11, 12, 4, 8, 44, 862, DateTimeKind.Local).AddTicks(1491)
                        },
                        new
                        {
                            Id = 12,
                            ClientCompany = "Aufderhar Inc",
                            ContractorCompany = "Harris and Sons",
                            EndDate = new DateTime(2025, 1, 7, 1, 52, 29, 413, DateTimeKind.Local).AddTicks(8117),
                            Name = "Project 12",
                            Priority = 1,
                            ProjectManagerId = 39,
                            StartDate = new DateTime(2024, 10, 28, 11, 28, 12, 452, DateTimeKind.Local).AddTicks(1504)
                        },
                        new
                        {
                            Id = 13,
                            ClientCompany = "Bechtelar - Jenkins",
                            ContractorCompany = "Schmeler Group",
                            EndDate = new DateTime(2025, 6, 21, 0, 18, 42, 237, DateTimeKind.Local).AddTicks(8529),
                            Name = "Project 13",
                            Priority = 4,
                            ProjectManagerId = 36,
                            StartDate = new DateTime(2023, 11, 20, 6, 18, 49, 233, DateTimeKind.Local).AddTicks(1613)
                        },
                        new
                        {
                            Id = 14,
                            ClientCompany = "Torphy Inc",
                            ContractorCompany = "Farrell Inc",
                            EndDate = new DateTime(2025, 2, 11, 14, 49, 55, 672, DateTimeKind.Local).AddTicks(4381),
                            Name = "Project 14",
                            Priority = 5,
                            ProjectManagerId = 36,
                            StartDate = new DateTime(2023, 3, 30, 17, 21, 54, 279, DateTimeKind.Local).AddTicks(3704)
                        },
                        new
                        {
                            Id = 15,
                            ClientCompany = "Reynolds - Kautzer",
                            ContractorCompany = "Hills - Koch",
                            EndDate = new DateTime(2025, 1, 21, 9, 24, 52, 371, DateTimeKind.Local).AddTicks(6101),
                            Name = "Project 15",
                            Priority = 2,
                            ProjectManagerId = 23,
                            StartDate = new DateTime(2024, 3, 25, 8, 55, 24, 805, DateTimeKind.Local).AddTicks(1455)
                        },
                        new
                        {
                            Id = 16,
                            ClientCompany = "Gutmann Inc",
                            ContractorCompany = "Schinner - Swaniawski",
                            EndDate = new DateTime(2025, 9, 29, 16, 27, 46, 318, DateTimeKind.Local).AddTicks(4020),
                            Name = "Project 16",
                            Priority = 3,
                            ProjectManagerId = 4,
                            StartDate = new DateTime(2022, 12, 5, 21, 53, 10, 101, DateTimeKind.Local).AddTicks(2465)
                        },
                        new
                        {
                            Id = 17,
                            ClientCompany = "Windler - Koss",
                            ContractorCompany = "Flatley LLC",
                            EndDate = new DateTime(2025, 10, 26, 5, 34, 40, 466, DateTimeKind.Local).AddTicks(3497),
                            Name = "Project 17",
                            Priority = 5,
                            ProjectManagerId = 46,
                            StartDate = new DateTime(2024, 8, 28, 13, 17, 5, 950, DateTimeKind.Local).AddTicks(2451)
                        },
                        new
                        {
                            Id = 18,
                            ClientCompany = "Gerlach, Altenwerth and Kris",
                            ContractorCompany = "Hilll Group",
                            EndDate = new DateTime(2025, 4, 30, 10, 5, 40, 795, DateTimeKind.Local).AddTicks(4386),
                            Name = "Project 18",
                            Priority = 2,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2023, 1, 9, 0, 54, 13, 458, DateTimeKind.Local).AddTicks(9954)
                        },
                        new
                        {
                            Id = 19,
                            ClientCompany = "Beahan LLC",
                            ContractorCompany = "Lesch - Haag",
                            EndDate = new DateTime(2025, 7, 15, 6, 29, 12, 974, DateTimeKind.Local).AddTicks(2066),
                            Name = "Project 19",
                            Priority = 3,
                            ProjectManagerId = 49,
                            StartDate = new DateTime(2024, 1, 19, 4, 11, 22, 624, DateTimeKind.Local).AddTicks(2081)
                        },
                        new
                        {
                            Id = 20,
                            ClientCompany = "Wuckert - Rosenbaum",
                            ContractorCompany = "Huel and Sons",
                            EndDate = new DateTime(2025, 8, 3, 18, 22, 24, 651, DateTimeKind.Local).AddTicks(4140),
                            Name = "Project 20",
                            Priority = 1,
                            ProjectManagerId = 44,
                            StartDate = new DateTime(2023, 5, 10, 18, 29, 7, 399, DateTimeKind.Local).AddTicks(2818)
                        });
                });

            modelBuilder.Entity("ProjectManagementApp.Models.ProjectEmployee", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectEmployees");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 6
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 16
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 46
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 13
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 47
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 12
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 49
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 35
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 19
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 28
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 35
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 23
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 22
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 50
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 15
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 46
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 11
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 48
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 7
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 45
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 9
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 41
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 6,
                            EmployeeId = 42
                        },
                        new
                        {
                            ProjectId = 6,
                            EmployeeId = 47
                        },
                        new
                        {
                            ProjectId = 6,
                            EmployeeId = 27
                        },
                        new
                        {
                            ProjectId = 6,
                            EmployeeId = 46
                        },
                        new
                        {
                            ProjectId = 6,
                            EmployeeId = 19
                        },
                        new
                        {
                            ProjectId = 7,
                            EmployeeId = 26
                        },
                        new
                        {
                            ProjectId = 7,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 7,
                            EmployeeId = 31
                        },
                        new
                        {
                            ProjectId = 7,
                            EmployeeId = 28
                        },
                        new
                        {
                            ProjectId = 7,
                            EmployeeId = 11
                        },
                        new
                        {
                            ProjectId = 8,
                            EmployeeId = 19
                        },
                        new
                        {
                            ProjectId = 8,
                            EmployeeId = 28
                        },
                        new
                        {
                            ProjectId = 8,
                            EmployeeId = 45
                        },
                        new
                        {
                            ProjectId = 8,
                            EmployeeId = 22
                        },
                        new
                        {
                            ProjectId = 8,
                            EmployeeId = 38
                        },
                        new
                        {
                            ProjectId = 9,
                            EmployeeId = 47
                        },
                        new
                        {
                            ProjectId = 9,
                            EmployeeId = 8
                        },
                        new
                        {
                            ProjectId = 9,
                            EmployeeId = 3
                        },
                        new
                        {
                            ProjectId = 9,
                            EmployeeId = 41
                        },
                        new
                        {
                            ProjectId = 9,
                            EmployeeId = 40
                        },
                        new
                        {
                            ProjectId = 10,
                            EmployeeId = 32
                        },
                        new
                        {
                            ProjectId = 10,
                            EmployeeId = 43
                        },
                        new
                        {
                            ProjectId = 10,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 10,
                            EmployeeId = 24
                        },
                        new
                        {
                            ProjectId = 10,
                            EmployeeId = 34
                        },
                        new
                        {
                            ProjectId = 11,
                            EmployeeId = 33
                        },
                        new
                        {
                            ProjectId = 11,
                            EmployeeId = 37
                        },
                        new
                        {
                            ProjectId = 11,
                            EmployeeId = 22
                        },
                        new
                        {
                            ProjectId = 11,
                            EmployeeId = 44
                        },
                        new
                        {
                            ProjectId = 11,
                            EmployeeId = 15
                        },
                        new
                        {
                            ProjectId = 12,
                            EmployeeId = 46
                        },
                        new
                        {
                            ProjectId = 12,
                            EmployeeId = 10
                        },
                        new
                        {
                            ProjectId = 12,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 12,
                            EmployeeId = 9
                        },
                        new
                        {
                            ProjectId = 12,
                            EmployeeId = 45
                        },
                        new
                        {
                            ProjectId = 13,
                            EmployeeId = 47
                        },
                        new
                        {
                            ProjectId = 13,
                            EmployeeId = 14
                        },
                        new
                        {
                            ProjectId = 13,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 13,
                            EmployeeId = 38
                        },
                        new
                        {
                            ProjectId = 13,
                            EmployeeId = 50
                        },
                        new
                        {
                            ProjectId = 14,
                            EmployeeId = 37
                        },
                        new
                        {
                            ProjectId = 14,
                            EmployeeId = 49
                        },
                        new
                        {
                            ProjectId = 14,
                            EmployeeId = 7
                        },
                        new
                        {
                            ProjectId = 14,
                            EmployeeId = 42
                        },
                        new
                        {
                            ProjectId = 14,
                            EmployeeId = 32
                        },
                        new
                        {
                            ProjectId = 15,
                            EmployeeId = 5
                        },
                        new
                        {
                            ProjectId = 15,
                            EmployeeId = 10
                        },
                        new
                        {
                            ProjectId = 15,
                            EmployeeId = 28
                        },
                        new
                        {
                            ProjectId = 15,
                            EmployeeId = 38
                        },
                        new
                        {
                            ProjectId = 15,
                            EmployeeId = 49
                        },
                        new
                        {
                            ProjectId = 16,
                            EmployeeId = 3
                        },
                        new
                        {
                            ProjectId = 16,
                            EmployeeId = 34
                        },
                        new
                        {
                            ProjectId = 16,
                            EmployeeId = 2
                        },
                        new
                        {
                            ProjectId = 16,
                            EmployeeId = 44
                        },
                        new
                        {
                            ProjectId = 16,
                            EmployeeId = 20
                        },
                        new
                        {
                            ProjectId = 17,
                            EmployeeId = 45
                        },
                        new
                        {
                            ProjectId = 17,
                            EmployeeId = 32
                        },
                        new
                        {
                            ProjectId = 17,
                            EmployeeId = 47
                        },
                        new
                        {
                            ProjectId = 17,
                            EmployeeId = 19
                        },
                        new
                        {
                            ProjectId = 17,
                            EmployeeId = 6
                        },
                        new
                        {
                            ProjectId = 18,
                            EmployeeId = 46
                        },
                        new
                        {
                            ProjectId = 18,
                            EmployeeId = 44
                        },
                        new
                        {
                            ProjectId = 18,
                            EmployeeId = 4
                        },
                        new
                        {
                            ProjectId = 18,
                            EmployeeId = 48
                        },
                        new
                        {
                            ProjectId = 18,
                            EmployeeId = 35
                        },
                        new
                        {
                            ProjectId = 19,
                            EmployeeId = 36
                        },
                        new
                        {
                            ProjectId = 19,
                            EmployeeId = 42
                        },
                        new
                        {
                            ProjectId = 19,
                            EmployeeId = 37
                        },
                        new
                        {
                            ProjectId = 19,
                            EmployeeId = 28
                        },
                        new
                        {
                            ProjectId = 19,
                            EmployeeId = 40
                        },
                        new
                        {
                            ProjectId = 20,
                            EmployeeId = 24
                        },
                        new
                        {
                            ProjectId = 20,
                            EmployeeId = 30
                        },
                        new
                        {
                            ProjectId = 20,
                            EmployeeId = 18
                        },
                        new
                        {
                            ProjectId = 20,
                            EmployeeId = 45
                        },
                        new
                        {
                            ProjectId = 20,
                            EmployeeId = 9
                        });
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Project", b =>
                {
                    b.HasOne("ProjectManagementApp.Models.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.ProjectEmployee", b =>
                {
                    b.HasOne("ProjectManagementApp.Models.Employee", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementApp.Models.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Employee", b =>
                {
                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Project", b =>
                {
                    b.Navigation("ProjectEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
